spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: RM98524
    password: 100603
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
